version: '3'
services:
  postgres:
    image: postgres:10
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: quizlingo_server
      POSTGRES_PASSWORD: postgres
#      PGDATA: /data
#    volumes:
#      - ./tools/AuthDBData:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/quizlingo_server
      QUIZLINGO_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    links:
      - postgres
  frontend-1:
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
  frontend-2:
    build:
      context: ./frontend/nextjs
      dockerfile: Dockerfile
    environment:
      PORT: 3001
    ports:
      - "3001:3001"